import { APP_ROUTE_META, APP_ROUTE_PATHS, APP_SEGMENT_LABELS, MAIN_NAV_ITEMS } from "./app.constants";
import { NOTES_ROUTE_META, NOTES_ROUTE_PATHS, NOTES_SEGMENT_LABELS } from "./notes.constants";
import {
  TOOL_ROUTE_PREFIX,
  TOOLS_ROUTE_META,
  TOOLS_ROUTE_PATHS,
  TOOLS_ROUTE_SEGMENTS,
  TOOLS_SEGMENT_LABELS,
} from "./tools.constants";

export const APP_ROUTES = {
  HOME: APP_ROUTE_PATHS.HOME,
  NOTE: APP_ROUTE_PATHS.NOTE,
  CONTACT: APP_ROUTE_PATHS.CONTACT,
  TOOLS: TOOLS_ROUTE_PATHS.ROOT,
  ROUGHFRAME: TOOLS_ROUTE_PATHS.ROUGHFRAME,
  NOTES: NOTES_ROUTE_PATHS.HOME,
  NOTE_DETAIL: NOTES_ROUTE_PATHS.DETAIL,
};

export const APP_ROUTE_PREFIXES = {
  TOOLS: TOOL_ROUTE_PREFIX,
};

export const ROUTE_META = {
  ...APP_ROUTE_META,
  ...NOTES_ROUTE_META,
  ...TOOLS_ROUTE_META,
};

export const BREADCRUMB_SEGMENT_LABELS = {
  ...APP_SEGMENT_LABELS,
  ...NOTES_SEGMENT_LABELS,
  ...TOOLS_SEGMENT_LABELS,
};

export { MAIN_NAV_ITEMS };
export { TOOLS_ROUTE_SEGMENTS };
